{
	"version": 1731817430,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/button_start.png",
		"images/spr_player_anim-sheet0.png",
		"images/spr_player_anim-sheet1.png",
		"images/spr_player_box-sheet0.png",
		"images/ui_contador_de_arvores.png",
		"images/ui_mapa1_textodeinicio2.png",
		"images/ui_selecionador_do_mapa-sheet0.png",
		"images/ui_selecionador_do_mapa-sheet1.png",
		"images/ui_borda_barradevida-sheet0.png",
		"images/ui_meio_barradevida-sheet0.png",
		"images/tm_ground.png",
		"images/spr_arvore-sheet0.png",
		"images/part_fogo.png",
		"images/spr_player_armas-sheet0.png",
		"images/spr_player_armas-sheet1.png",
		"images/part_fumaca.png",
		"images/spr_part_agua-sheet0.png",
		"images/coll_mira-sheet0.png",
		"images/tb_fade_da_tela.png",
		"images/ui_armas_selecionadas1-sheet0.png",
		"images/ui_seta_de_selecao-sheet0.png",
		"images/ui_armas_selecionadas2-sheet0.png",
		"images/ui_armas_selecionadas3-sheet0.png",
		"images/ui_armas_selecionadas4-sheet0.png",
		"images/ui_armas_selecionadas5-sheet0.png",
		"images/spr_part_recic_azul-sheet0.png",
		"images/coll_dano_melee-sheet0.png",
		"images/spr_enemy_fogo_anim-sheet0.png",
		"images/spr_enemy_fogo_box-sheet0.png",
		"images/spr_apontar_fogo-sheet0.png",
		"images/ui_box_das_armas-sheet0.png",
		"images/spr_part_recic_amarelo-sheet0.png",
		"images/spr_enemy_plastico-sheet0.png",
		"images/spr_enemy_plastico-sheet1.png",
		"images/sor_explosion_plastico-sheet0.png",
		"images/sor_explosion_plastico-sheet1.png",
		"images/spr_part_recic_verde-sheet0.png",
		"images/spr_decoracao_chao-sheet0.png",
		"images/spr_button_start-sheet0.png",
		"images/spr_button_start2-sheet0.png",
		"images/spr_button_start3-sheet0.png",
		"images/tl_solid.png",
		"images/tm_solid.png",
		"media/retro explosion short 01.m4a",
		"media/retro explosion short 01.ogg",
		"media/retro explosion short 15.m4a",
		"media/retro explosion short 15.ogg",
		"media/retro explosion swoshes 04.m4a",
		"media/retro explosion swoshes 04.ogg",
		"media/retro water drop 01.m4a",
		"media/retro water drop 01.ogg",
		"media/retro event complex 03.m4a",
		"media/retro event complex 03.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}